### ISSUE TITLE
Sugestão: Por que não fazer Mobile?

### ISSUE THREAD

**Issue by glandre** [JhonnatanNakano/Emulador-casio#3]
Pelo detalhamento da descrição parece bastante adequado ser implementado como Aplicativo Mobile.
Dêem uma olhada no Xamarin que é um Framework em C# Multiplataforma Mobile e integrado com o Visual Studio.
https://www.xamarin.com/visual-studio

**Comment by JhonnatanNakano** [comment]
Escolhemos
